# TODO: complete this in class
language: cpp
python:
compiler: gcc
script: make && make test


#notifications section
notifications:
    email:
        recipients:
            - novakam1@gcc.edu
            - suttonle1@gcc.edu
            - lundbergmj1@gcc.edu
        on_sucess: always #default: change
        on_failure: always #default: always
